name: API Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # Roda a cada 5 minutos (tempo do idle)

jobs:
  alive_check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /alive endpoint
        run: |
          echo "Pingando a API..."
          curl -X GET https://api-pg-purpura-latest.onrender.com/alive
